### PR TITLE
Fix KV File Indexing

### PR DESCRIPTION
**Pull request by MalachiPyronomicon**
Index 'i' was not incremented after the last file read, leaving 'g_iServerCount' one short.

### CODE REVIEW

**Comment by JoinedSenses** [comment]
I'll review soon when I have more time. Didn't test my changes (definitely should have), so I maybe I should have done `++i` instead of `i++` or `<=` instead of `<`. Not thrilled about all the debug messages added into a fix for incremental error, but maybe that's due to my current state of sleep deprivation.

**Comment by MalachiPyronomicon** [comment]
Moving the "i++" out of the do/while test (line 126) is the fix. The && evaluates left-to-right. When GoToNextKey() fails, it skips over the rest of the test and continues execution after the loop.

**Comment by JoinedSenses** [comment]
Edit: Had another message but removed it since I should wait until I get home.

**Comment by JoinedSenses** [comment]
If you get the chance, could you modify it to:

```while (++i <= MAX_SERVERS && kv.GotoNextKey());

if (i > MAX_SERVERS) {```

**Pull request merged**
