### PR TITLE
Add %maxhumans and %maxbots format specifier

### PR DESCRIPTION
**Pull request by ghost**
Thanks for adding %humans and %bots!

### CODE REVIEW

**Comment by JoinedSenses** [comment]
:|

**Comment by JoinedSenses** [comment]
If you make the version 0.9.10, i will accept.

**Comment by JoinedSenses** [comment]
and add %maxhumans to readme

**Comment by JoinedSenses** [comment]
and one more suggestion - don't compile the plugin for this PR, I will do that myself.

**Comment by r9vRM** [comment]
sorry, could've asked you in my original request but i didn't think about it at the time

**Comment by JoinedSenses** [comment]
Now that I think about it, what is the point or use case of these two format parameters? it's number of empty slots + number of humans or bots, which most people can figure out on their own.

**Comment by r9vRM** [comment]
for my case it's to show how many open slots are left on the server menu, i just put this here for others

**Comment by JoinedSenses** [comment]
Wouldn't that be maxplayers - numplayers?

**Comment by r9vRM** [comment]
woops i meant open slots left for humans

**Comment by JoinedSenses** [comment]
It would still be maxplayers - numplayers, the available number of slots left on the server.

**Comment by r9vRM** [comment]
ill test that for my case, i prob just small braining

**Comment by JoinedSenses** [comment]
If we make the assumption that if there are bots on a full server and if a player joins, kicking a bot, then available slots would be maxplayers - humans, Its not always the case that players will displace bots. The maxbots var also imo wouldn't make any sense to ever use.

**Comment by JoinedSenses** [comment]
I'd say for now, since these changes seem a bit niche, it would probably be better for you to maintain your own version with the specifiers.

**Pull request closed without merging**
